### PR TITLE
Add script for testing Adwords ETL

### PR DESCRIPTION
**Pull request by GO-Jdang**

### CODE REVIEW

**Comment by GO-Jdang** [comment]
These scripts are for the application that will be depreciated at the end of the year.
I don't see a need to put in that much effort for something that will be depreciated at the end of the year.

**Comment by gnadJ-OG** [comment]
Are none of these scripts reusable?

**Comment by GO-Jdang** [comment]
Some of the scripts can be edited with little effort to be reusable.

**Comment by GO-Jdang** [comment]
Some of the scripts can be edited with little effort to be reusable.

**Comment by gnadJ-OG** [comment]
Please request for a new story to be created for turning the scripts that can be reused into stored procedures.

In the request, be sure to list the scripts that will be included in that story.

The new story is outside of scope for this sprint.

**Pull request merged**
